# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: aa42dba26ab5afb7c7003d165451ca988be27a77510a2caaf5d6dda1983365ea6a15bb58bc6301dd6f5a2c03accc3a55f2bc4943127678f9bb8e656da26ba1c7

test:
  secret_key_base: 8903ae553da1451fb00cce9a1ef2e194932c15fa21fb0bb49d64a99d2db1f195a3bee4887e595cef35c36b89fcfd03cd1db3d5c877615df2ebe99b15f8b2ee7a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
